Add check for directories with the same name as the filename.

diff --git a/sup b/sup
--- a/sup
+++ b/sup
@@ -17,12 +17,13 @@ createRepo() {
     answer=""
     while [ "$answer" != "y" -o "$answer" != "n" ]
     do 
-        echo "Repository does not exist. Create a public repository? (Requires GitHub-cli) (y/n)"
+        echo "Repository doesn't exist. Create a public repository? (Requires GitHub-cli) (y/n)"
         read answer
         if [ "$answer" == "y" ]; then
             eval "gh repo create $projectName --public"
             break
         elif [ "$answer" == "n" ]; then
+            printf "\033[0;31mAborted\n"
             exit 1
         fi
     done
@@ -44,11 +45,16 @@ if [ "$projectName" == "" ]; then
     exit 1
 fi
 
+if [ -d "./$projectName" ]; then
+    printf "\033[0;31mDirectory with the project name already exists!\033[0m\n"
+    exit 1
+fi
+
 if [ $git -eq 0 ]; then
     statusCode=$(curl --write-out %{http_code} --silent --output /dev/null https://github.com/$userName/$projectName)
     case $statusCode in
         404) createRepo;;
-        000) printf "Cannot connect to the remote repository."
+        000) printf "\033[0;31mCannot connect to the remote repository!\033[0m\n"
              exit 1;;
         *) eval "git clone git@github.com:$userName/$projectName.git";;
     esac
